# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout

      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false ha-arti
            ./jfrog rt pipc --repo-resolve=remote-pypi --server-id-resolve=ha-arti
            ./jfrog rt pipi -r requirements.txt --build-name=circleci-pip-build --build-number=$CIRCLE_BUILD_NUM --module=jfrog-python-example --trusted-host 35.207.143.222
            ./jfrog rt u dist/ onboard-pypi-repo-local --build-name=circleci-pip-build --build-number=$CIRCLE_BUILD_NUM --module=jfrog-python-example --server-id=ha-arti
#            ./jfrog rt u <path/to/artifact> <artifactory_repo_name> --build-name=<name_you_give_to_build> --build-number=$CIRCLE_BUILD_NUM
#            ./jfrog rt bce <name_you_give_to_build> $CIRCLE_BUILD_NUM  # collects all environment variables on the agent